const contactActionTypes = {
  GET_CONTACTS_REQUEST: "GET_CONTACTS_REQUEST",
  GET_CONTACTS_RESPONSE: "GET_CONTACTS_RESPONSE",
  GET_CONTACTS_ERROR: "GET_CONTACTS_ERROR",
  GET_CONTACTS_CLEAR: "GET_CONTACTS_CLEAR",
};
export default contactActionTypes;
